### ISSUE TITLE
Add Room Option - Invalid Room Capacity Acceptance

### ISSUE THREAD

**Issue by vivekVells** [gentig/MSCS721-roomScheduler#4]
Issue: Acceptance of invalid room capacity input

Replication Steps:
Input the room and then for the capacity of the room, input the followings (all will be accepted though invalid)
- 0
- 999999999
- Negative numbers (-22)

Kindly refer the attached screenshot for reference.
![addroominvalidroomcapacityacceptance](https://user-images.githubusercontent.com/25471383/36348342-60d7fb74-143b-11e8-99d5-3817a712b48e.PNG)

- [x] Completed

**Comment by gentig** [comment]
This bug is fixed
