### ISSUE TITLE
Add Room Option - Program Breakdown or Exits with errors

### ISSUE THREAD

**Issue by vivekVells** [gentig/MSCS721-roomScheduler#5]
Issue: Program breakdown or exits with errors

Replication Steps:
Input the room and then for the capacity of the room, input the followings (all will result in breaking down the program without being handled properly)
- 999999999999999999999999999999999999 
- &*&*
- alphabets 

Kindly refer the attached screenshot for reference.
![addroominvalidroomcapacityinputprogrambreakdown](https://user-images.githubusercontent.com/25471383/36348358-de1106bc-143b-11e8-99bf-aac2ae52d998.PNG)

- [x] Completed

**Comment by gentig** [comment]
This bug is fixed
