### ISSUE TITLE
Remove Room - program breakdown  or program exits with errors 

### ISSUE THREAD

**Issue by vivekVells** [gentig/MSCS721-roomScheduler#6]
Issue: Program breakdown or exits with errors

Replication Steps:
Select remove room and then input the followings (all will result in breaking down the program without being handled properly)
- when no rooms available to remove (when pgm starts initially)
- when no such room available 
- symbols (%$^%$)

Kindly refer the attached screenshot for reference.
![removeroompgmbreakdown](https://user-images.githubusercontent.com/25471383/36348376-3d2eadde-143c-11e8-9a4e-4399d5224490.PNG)

- [x] Completed

**Comment by gentig** [comment]
This bug is fixed
