### ISSUE TITLE
Schedule Room - Invalid input acceptance & Program Breakdown

### ISSUE THREAD

**Issue by vivekVells** [gentig/MSCS721-roomScheduler#7]
Issue: Acceptance of invalid inputs of room schedule

Replication Steps:
Select room schedule option and then input the followings (all will be accepted though invalid)
- Past year, date, month
- Any room name that was not created that leads to breakdown

Program breakdown
- Invalid entries (numbers, alphabets, symbols) parse problems
- non-scheduled roomname

Kindly refer the attached screenshot for reference.
![scheduleroominvalidbkdown](https://user-images.githubusercontent.com/25471383/36348399-e1f4cc40-143c-11e8-90d8-0658ac10f91c.PNG)

- [x] Completed

**Comment by gentig** [comment]
This bug is fixed
