### ISSUE TITLE
List Schedule- program breakdown or exits with errors

### ISSUE THREAD

**Issue by vivekVells** [gentig/MSCS721-roomScheduler#8]
Issue: Program breakdown or exits with errors

Replication Steps:
Select List Schedule room option and then input the followings (all will result in breaking down the program without being handled properly)
- Invalid entries (numbers, alphabets, symbols)
- non-scheduled roomname
![listschedulepgmbkdwn](https://user-images.githubusercontent.com/25471383/36348411-552b75b0-143d-11e8-9563-b37f663ff6b6.PNG)

Kindly refer the attached screenshot for reference.

- [x] Completed

**Comment by gentig** [comment]
This bug is fixed

- [ ] Completed
