### ISSUE TITLE
Unable to test import and export feature 

### ISSUE THREAD

**Issue by vivekVells** [gentig/MSCS721-roomScheduler#9]
Unable to test the import and export feature of this program. Kindly advise or comment how to proceed further for this

- [x] Completed

**Comment by gentig** [comment]
This bug is fixed (I knew it would fail because I forgot to commit changes for these errors, but thank you). To test this just run the program, add some rooms and choose export from menu, then look into jsonfiles folder from the project root, json files will be there

- [ ]
